spring:
  application:
    name: team-query-service
  data:
    mongodb:
      database: projectDatabase
      uri: mongodb://localhost:27017/projectDatabase
      authentication-database: projectDatabase
  kafka:
    bootstrap-servers: localhost:10094
    consumer:
      group-id: team-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
server:
  address: '0.0.0.0'
  port: 10042
env:
  kafka:
    topicEvent: team-event